routes/web.php
<?php
//web routes---------------------------------------------------
Route::get('/', [
    'uses' => 'FrontEndController@index',
    'as' => 'index'
]);

Route::get('/cms/dashboard', function(){
    $somePosts = \App\Post::where('title', 'like', '%'.request('query').'%')->paginate(6);
    return view('cms.dashboard')->with('posts', $somePosts)
                            ->with('title', 'Search: '.request('query'))
                            ->with('categories', \App\Category::all())
                            ->with('settings', \App\Setting::first())
                            ->with('query', request('query'));
});


Route::get('/article/{slug}', [
    'uses' => 'FrontEndController@singlePost',
    'as' => 'post.single'
]);

Route::get('/article', [
    'uses' => 'FrontEndController@postCategories',
    'as' => 'post.categories'
]);

Route::get('/category/{slug}', [
    'uses' => 'FrontEndController@singleCategory',
    'as' => 'single.category'
]);

Route::get('/news', [
    'uses' => 'FrontEndController@news',
    'as' => 'news.list'
]);

Route::get('/news/{slug}', [
    'uses' => 'FrontEndController@singleNews',
    'as' => 'page.single'
]);

Route::get('/profile', [
    'uses' => 'FrontEndController@profile',
    'as' => 'profile.list'
]);

Route::get('/profile/{slug}', [
    'uses' => 'FrontEndController@singleProfile',
    'as' => 'profile.single'
]);

Route::get('/download', [
    'uses' => 'FrontEndController@downloadPage',
    'as' => 'file.list'
]);

Route::get('/files/{file}', [
    'uses' => 'FrontEndController@downloadFile',
    'as' => 'file.download'
]);

Route::get('/savings', [
    'uses' => 'FrontEndController@savings',
    'as' => 'savings'
]);

Route::get('/results', function(){
    $somePosts = \App\Post::where('title', 'like', '%'.request('query').'%')->paginate(6);
    return view('results')->with('posts', $somePosts)
                            ->with('title', 'Search: '.request('query'))
                            ->with('categories', \App\Category::all())
                            ->with('settings', \App\Setting::first())
                            ->with('query', request('query'));
});



//CMS Routes----------------------------------------------------------
Auth::routes();
Route::group(['prefix' => 'cms', 'middleware' => 'auth'], function(){
    
    Route::get('/dashboard', function(){
        return view('cms.dashboard');
    });
    

    Route::get('/home', 'HomeController@index')->name('home');
    
    Route::resources([
        'post' => 'CMS\PostsController',
        'category' => 'CMS\CategoriesController',
        'tag' => 'CMS\TagsController',
        'user' => 'CMS\UsersController',
        'file' => 'CMS\FilesController',
        'image' => 'CMS\ImagesController',
        'page' => 'CMS\PagesController'
    ]);

    Route::get('settings', [
        'uses' => 'CMS\SettingsController@index',
        'as' => 'settings'
    ]);
    
    Route::get('posts/trashed', [
        'uses' => 'CMS\PostsController@trashed',
        'as' => 'post.trashed'
    ]);

    Route::get('/post/restore/{post}', [
        'uses' => 'CMS\PostsController@restore',
        'as' => 'post.restore'
    ]);   

    Route::get('/post/kill/{post}', [
        'uses' => 'CMS\PostsController@kill',
        'as' => 'post.kill'
    ]);   

    Route::get('/settings', [
        'uses' => 'CMS\SettingsController@index',
        'as' => 'settings'
    ]);

    Route::get('/user/profile', [
        'uses' => 'CMS\ProfilesController@index',
        'as' => 'user.profile'
    ]);

    Route::post('/user/profile/update', [
        'uses' => 'CMS\ProfilesController@update',
        'as' => 'user.profile.update'
    ]);

    Route::post('/settings/update', [
        'uses' => 'CMS\SettingsController@update',
        'as' => 'settings.update'
    ]);

    Route::get('/user/not-admin/{user}', [
        'uses' => 'CMS\UsersController@not_admin',
        'as' => 'admin.demote'
    ])->middleware('admin');

    Route::get('/user/admin/{user}', [
        'uses' => 'CMS\UsersController@admin',
        'as' => 'admin.promote'
    ])->middleware('admin');
    

});

app/Http/Controllers/CMS/CategoriesController.php
<?php

namespace App\Http\Controllers\CMS;

use App\Category;
use Session;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CategoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        return view('cms.categories.index')->with('categories', Category::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('cms.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $this->validate($request,[
            'name' => 'required'
        ]);
        $category = new Category;

        $category->name = $request->name;
        $category->description = "hehe";
        $category->slug = str_slug($request->name);
        $category->save();

        Session::flash('success', 'You successfully created a category');
        return redirect()->route('category.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $category = Category::find($id);
        return view('cms.categories.edit')->with('category', $category);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $category = Category::find($id);

        $category->name = $request->name;

        $category->save();

        
        Session::flash('success', 'You successfully updated a category');
        return redirect()->route('category.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $category = Category::find($id);

        foreach($category->posts as $post){
            $post->delete();
        }


        $category->delete();
        
        Session::flash('success', 'You successfully deleted a category');
        return redirect()->back();

    }
}

app/Http/Controllers/CMS/FilesController.php
<?php

namespace App\Http\Controllers\CMS;

use App\Category;
use App\File;
use Session;
use Illuminate\Support\Facades\Storage;


use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class FilesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        return view('cms.files.index')->with('files', File::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('cms.files.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $this->validate($request,[
            'name' => 'required',
            'description' => 'required'
        ]);
        
        if($request->hasFile('featured'))
        {
            $featured = $request->featured;
            $featured_new_name = time().$featured->getClientOriginalName();
            $featured->storeAs('public/files', $featured_new_name);
   
            $file_link = 'files/'.$featured_new_name;
        } else {
            $file_link = $request->url;
        }

        $file = File::create([
            'name' => $request->name,
            'description' => $request->description,
            'featured' =>  $file_link,
            'slug' => str_slug($request->name),
        ]);

        Session::flash('success', 'You successfully created a file');
        return redirect()->route('file.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $file = File::find($id);
        return view('cms.files.edit')->with('file', $file);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required',
            'description' => 'required|max:191',
        ]);

        $file = File::find($id);

        if($request->hasFile('featured'))
        {
            if(is_file(storage_path('app/public/' . $file->featured)))
            {
                unlink(storage_path('app/public/' . $file->featured));
            }
            
            $avatar = $request->featured;
            $avatar_new_name = time().$avatar->getClientOriginalname();

            $avatar->storeAs('public/files', $avatar_new_name);

            $file->featured = 'files/'.$avatar_new_name;
        } else {
            $file->featured = $request->url;
        }
        $file->name = $request->name;
        $file->description =$request->description;


        $file->save();

        
        Session::flash('success', 'You successfully updated a file');
        return redirect()->route('file.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $file = file::find($id);

        if(is_file(storage_path('app/public/' . $file->featured)))
        {
            unlink(storage_path('app/public/' . $file->featured));
        }

        $file->delete();
        
        Session::flash('success', 'You successfully deleted a file');
        return redirect()->back();

    }
}

app/Http/Controllers/CMS/FinancesController.php
<?php

namespace App\Http\Controllers\CMS;

use App\Finance;
use Session;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class FinancesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/CMS/ImagesController.php
<?php

namespace App\Http\Controllers\CMS;

use App\Image;
use Session;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ImagesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('cms.images.index')->with('images', Image::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('cms.images.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $this->validate($request,[
            'name' => 'required',
            'featured' => 'image|required|unique:images'
        ]);

        
        $image = new Image;
        
        if($request->hasFile('featured'))
        {
            $featured = $request->featured;
            $avatar_new_name = str_slug($request->name).'.png';
            $featured->storeAs('public/background_images', $avatar_new_name);

            $image_link = 'background_images/' . $avatar_new_name;
        }
        else
        {
            return redirect()->back();
        }

        $image->name = $request->name;
        $image->setting_id = 1;
        $image->featured = $image_link;
        $image->slug = str_slug($request->name);

        $image->save();

        Session::flash('success', 'You successfully created an image');
        return redirect()->route('image.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $image = Image::find($id);
        return view('cms.images.edit')->with('image', $image);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        
        $this->validate($request, [
            'name' => 'required',
        ]);

        $image = Image::find($id);
        if($request->name != $image->name){
            Session::flash('success', 'You cannot change the name');
            return redirect()->route('image.index');
        }

        if($request->hasFile('featured'))
        {
            if(is_file(storage_path('app/public/' . $image->featured)))
            {
                unlink(storage_path('app/public/' . $image->featured));
            }
            
            $avatar = $request->featured;
            $avatar_new_name = str_slug($request->name).'.png';

            $avatar->storeAs('public/background_images/', $avatar_new_name);

            $image->featured = 'background_images/'.$avatar_new_name;
        } else {
            Session::flash('success', 'You successfully make an error');
            return redirect()->route('image.index');
        }
        $image->name = $request->name;
        $image->save();

        
        Session::flash('success', 'You successfully updated a file');
        return redirect()->route('image.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $image = Image::find($id);

        if(is_file(storage_path('app/public/' . $image->featured)))
        {
            unlink(storage_path('app/public/' . $image->featured));
        }

        $image->delete();
        
        Session::flash('success', 'You successfully deleted an image');
        return redirect()->back();
    }
}

app/Http/Controllers/CMS/SettingsController.php
<?php

namespace App\Http\Controllers\CMS;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Setting;
use Session;

class SettingsController extends Controller
{
    public function __construct()
    {
        //$this->middleware('admin');
    }

    public function index()
    {
        return view('cms.settings.settings')->with('settings', Setting::first());
    }

    public function update()
    {
        $this->validate(request(), [
            'site_name' => 'required',
            'contact_number' => 'required',
            'contact_email' => 'required',
            'address' => 'required',
        ]);


        $settings = Setting::first();

        $settings->site_name = request()->site_name;
        $settings->address = request()->address;
        $settings->contact_email = request()->contact_email;
        $settings->contact_number = request()->contact_number;

        $settings->save();

        Session::flash('success', 'Settings updated');
        return redirect()->back();
    }
}

resources/views/cms/posts/index.blade.php
@extends('cms.layouts.app3')

@section('css')

@endsection

@section('scripts')
<script>
  $(function () {
    $("#example2").DataTable();
    $('#posts-table').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": true,
      "info": true,
      "autoWidth": false,
    });
  });
</script>
@endsection

@section('content-header')
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">Dashboard</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Dashboard v2</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
@endsection

@section('content')
    <section class="content">
      <div class="container-fluid">
        <!-- Small boxes (Stat box) -->
        <div class="row">
          <div class="col-lg-12">
            <div class="card">
              <div class="card-body">
                <a href="{{route('post.create')}}" class="btn btn-success"><i class="nav-icon fa fa-plus-square mr-2"></i>Add Post</a>
              </div>
            </div>
          </div>
        </div> 
        <div class="row">
          <div class="col-lg-12">
          <div class="card">
            <div class="card-header">
              <h3 class="card-title">List of Posts</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body table-responsive">
              <table id="posts-table" class="table table-bordered table-striped ">
                <thead>
                <tr>
                  <th>Featured Image</th>
                  <th>Title</th>
                  <th>Author</th>
                  <th>Tags</th>
                  <th>Creation Date</th>
                  <th>Action</th>
                </tr>
                </thead>
                <tbody>
                @foreach($posts as $post)
                <tr>
                  <td><img src="{{$post->featured}}" alt="{{$post->title}}" width="160px" height="90px"></td>
                  
                  <td>{{$post->title}}</td>
                  <td>{{$post->user->name}}</td>
                  <td>
                    @foreach($post->tags as $tag)
                      <span class="badge badge-info">{{$tag->tag." "}}</span>
                    @endforeach
                  </td>
                  <td>{{$post->created_at}}</td>
                  <td>
                    <form action="{{route('post.destroy', ['post' => $post->id])}}" method="POST">
                      @method('DELETE')
                      {{csrf_field()}}
                      <div class="btn-group-vertical w-100">
                        <a href="{{route('post.show', ['post' => $post->id])}}" class="btn btn-success btn-sm"><i class="nav-icon fa fa-eye mr-2"></i>View</a>
                        <a href="{{route('post.edit', ['post' => $post->id])}}" class="btn btn-primary btn-sm"><i class="nav-icon fa fa-pencil-square-o mr-2"></i>Edit</a>
                        <button type="submit" class="btn btn-danger btn-sm"><i class="nav-icon fa fa-trash-o mr-2"></i>Trash</button>
                      </div>
                    </form>
                  </td>
                </tr>
                @endforeach

                </tbody>
                <tfoot>
                <tr>
                  <th>Featured Image</th>
                  <th>Title</th>
                  <th>Author</th>
                  <th>Tags</th>
                  <th>Creation Date</th>
                  <th>Action</th>
                </tr>
                </tfoot>
              </table>
            </div>
            <!-- /.card-body -->
          </div>
        </div>
      </div>
    </div>
  </section>
@endsection

resources/views/cms/posts/posts-page.blade.php
@extends('cms.layouts.app3')

@section('css')
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
<link href='{{asset('css/froala_editor.pkgd.min.css')}}' rel='stylesheet' type='text/css' />
<link href='{{asset('css/froala_style.min.css')}}' rel='stylesheet' type='text/css' />
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>

@endsection

@section('js')

<script type='text/javascript' src='{{asset('js/froala_editor.pkgd.min.js')}}'></script>
<script>
    $(document).ready(function() {
        $('#summernote').froalaEditor();
    });
</script>
<script>
    $(document).ready(function() {
        $('#posts-table').DataTable({
            "scrollX": true,
            "lengthChange": false
        });
    } );
</script>
@endsection

@section('content')
<div class="row">
    <ul class="tabs">
        <li class="tab col s6"><a href="#test1">Post Lists</a></li>
        <li class="tab col s6"><a href="#test2">Add Post</a></li>
    </ul>
    <div id="test1" class="col s12">
        <div class="row">
            <div class="col s12">
                <div class="container">
                    <h3 class="header">List of Posts</h3>
                    <table id="posts-table">
                        <thead>
                            <tr>
                                <th>Featured Image</th>
                                <th>Title</th>
                                <th>Author</th>
                                <th>Tags</th>
                                <th>Creation Date</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($posts as $post)
                            <tr>
                            <td><img src="{{$post->featured}}" alt="{{$post->title}}" width="160px" height="90px"></td>
                            
                            <td>{{$post->title}}</td>
                            <td>{{$post->user->name}}</td>
                            <td>
                                @foreach($post->tags as $tag)
                                <span class="badge badge-info">{{$tag->tag." "}}</span>
                                @endforeach
                            </td>
                            <td>{{$post->created_at}}</td>
                            <td>
                                <form action="{{route('post.destroy', ['post' => $post->id])}}" method="POST">
                                @method('DELETE')
                                {{csrf_field()}}
                                <div class="btn-group-vertical w-100">
                                    <a href="{{route('post.show', ['post' => $post->id])}}" class="waves-effect waves-light btn-small col s12"><i class="material-icons left">cloud</i>View</a>
                                    <a href="{{route('post.edit', ['post' => $post->id])}}" class="waves-effect waves-light btn-small col s12"><i class="material-icons left">cloud</i>Edit</a>
                                    <button type="submit" class="waves-effect waves-light btn-small col s12"><i class="material-icons left">cloud</i></i>Trash</button>
                                </div>
                                </form>
                            </td>
                            </tr>
                            @endforeach
        
                        </tbody>
                        <tfoot>
                            <tr>
                                <th>Featured Image</th>
                                <th>Title</th>
                                <th>Author</th>
                                <th>Tags</th>
                                <th>Creation Date</th>
                                <th>Action</th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div id="test2" class="col s12">
        <div class="row">
            <div class="container">
                    @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <h3 class="header">Add New Post</h3>
                <form action="{{ route('post.store') }}" method="post" enctype="multipart/form-data">
                  {{ csrf_field() }}
                    <div class="input-field col s12">
                        {{-- <i class="material-icons prefix">textsms</i> --}}
                        <input type="text" name="title" id="title">
                        <label for="title">Title</label>
                    </div>
                    <div class="file-field input-field col s12">
                            <div class="btn">
                              <span>Featured Image</span>
                              <input type="file" name="featured" id="featured">
                            </div>
                            <div class="file-path-wrapper">
                              <input class="file-path validate" type="text">
                            </div>
                          </div>
                  <div class="input-field col s12">
                    <select name="category_id">
                        <option value="" disabled selected>Select a Category</option>
                        @foreach($categories as $category)
                            <option value="{{ $category->id }}">{{ $category->name }}</option>
                        @endforeach
                    </select>
                    <label>Category</label>
                    </div>
                    <div class="input-field col s12">
                        <p><label>
                            Tags
                        </label></p>
                        @foreach($tags as $tag)
                        <p>
                            <label>
                                <input type="checkbox"  class="filled-in" value="{{ $tag->id }}" name="tags[]">
                                <span>{{ $tag->tag }}</span> 
                            </label>
                        </p>
                        @endforeach
                    </div>

                    <div class="input-field col s12">
                        <textarea name="content" id="summernote">
                                &lt;p&gt;Here goes the initial content of the editor.&lt;/p&gt;
                        </textarea>
                        <label for="summernote">Content</label>
                    </div> 
                    <div class="input-field col s12">
                        <button class="btn waves-effect waves-light" type="submit" name="action">Submit
                            <i class="material-icons right">send</i>
                        </button>
                        <div>
                            <script async src="https://imgbb.com/upload.js" data-palette="blue" data-sibling-pos="before"></script>
                        </div>
                    </div>
                </form>

            </div>
        </div>
        
    </div>
</div>
@endsection

resources/views/cms/posts/show.blade.php
@extends('cms.layouts.app3')

@section('css')

@endsection

@section('scripts')

@endsection

@section('content')
<section class="content">
    <div class="container-fluid">
        <!-- Small boxes (Stat box) -->
        <div class="row">
            <div class="col s12">
                <div class="card">
                    <div class="card-content">
                        <a href="{{ URL::previous() }}" class="waves-effect waves-light btn-small"><i class="fa fa-arrow-circle-left mr-2"></i>Back</a>
                        <form action="{{route('post.destroy', ['post' => $post->id])}}" class="right" method="POST">
                            <a href="{{route('post.edit', ['post' => $post->id])}}" class="waves-effect waves-light btn-small"><i class="fa fa-pencil-square-o mr-2"></i>Edit Post</a>
                            <button type="submit" class="waves-effect waves-light btn-small"><i class="nav-icon fa fa-trash-o mr-2"></i>Trash</button>
                            @method('DELETE')
                            {{csrf_field()}}
                        </form>
                    </div>
                </div>
            </div>
            <div class="col s12">
                <div class="card">
                    <div class="card-image">
                        <img src="{{$post->featured}}" alt="{{$post->title}}" style="width:100%; height:auto;">
                        <span class="card-title">{{$post->title}}</span>
                    </div>
                    <div class="card-content">
                        <div class="container">
                            {!!$post->content!!}
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</section>
@endsection